name: Build and Package JavaFX App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Since we're targeting a Windows .exe file
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'   # Use Temurin JDK
          java-version: '21'        # Specify Java version 21

      - name: Install JavaFX SDK 21
        run: |
          # JavaFX isn't bundled with JDK, so we download it
          curl -Lo javafx-sdk.zip https://download2.gluonhq.com/openjfx/21.0.0.0/openjfx-21.0.0.0_windows-x64_bin-sdk.zip
          unzip javafx-sdk.zip -d $HOME/javafx-sdk

      - name: Build the project using Gradle (or Maven)
        run: |
          ./gradlew build  # or ./mvnw package for Maven
        shell: bash

      - name: Package to EXE using jpackage
        run: |
          jpackage --input build/libs/ --main-jar yourapp.jar --main-class com.janisbe.ZmieniarkaZnakow \
          --name MyApp --type exe --runtime-image $HOME/javafx-sdk --icon path/to/icon.ico
        shell: bash

      - name: Upload the packaged EXE as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: zmieniarka.exe
          path: ./zmieniarka.exe
